lifecycle:
  start:
    - command: echo 'Start database here'
      timeout: 30000
    - command: sleep 5
      timeout: 10000
    - command: pnpm dev
      keepAlive: true
      envs:
        TEST: value
        ANOTHER_TEST: anothervalue
  stop:
    - command: echo 'Stop database here'
      timeout: 10000
screenshots:
  diffThreshold: 0
output:
  console: true
  text: true
