lifecycle:
  start:
    - command: "echo 'Start database here'"
      timeout: 30000
    - command: "pnpm dev"
      keepAlive: true
  stop:
    - command: "echo 'Stop database here'"
      timeout: 10000

screenshots:
  diffThreshold: 0 # percentage of pixels that can differ (0-100).

output:
  console: true
  text: true
