name: Prevent PRs to main

on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR targets main
        run: |
          echo "Direct pull requests to 'main' are not allowed. Use tags to promote from dev to main."
          exit 1
